engines:
    duplication:
        enabled: true
        config:
            languages:
                - javascript
        exclude_paths:
            - "test/"
    fixme:
        enabled: true
    markdownlint:
        enabled: true
ratings:
    paths:
        - "**.js"
        - "**.md"
